name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and run devcontainer
      uses: docker/build-push-action@v5
      with:
        context: .
        file: .devcontainer/Dockerfile
        platforms: linux/amd64
        push: false
        load: true
        tags: devcontainer:latest

    - name: Run CMake build and tests
      run: |
        docker run --rm -v $(pwd):/workspace devcontainer:latest \
          bash -c "mkdir -p build && cd build && cmake .. && cmake --build . && ctest"
